print("This program takes two numbers and compares them using comparison operators.")
a=int(input("enter first number :"))
b=int(input("enter second number :"))

print("a>=b is A greater than or equal to B? :", a>=b)
print("a<=b is A less than or equal to B? :", a<=b)
print("a==b is A equals to B ?:", a==b)
print("a!=b is A not equal to B? :" , a!=b)
print("a>b is A greater than B? :", a>b)
print( "a<b is A less than B? :", a<b)
